[package]
name = "cursescurmnger"
version = "0.1.1"
description = "An app to manage custom Window cursor themes."
authors = ["Robert Elijah \"KiCKinTheBucket\" Reyes"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "cursescurmnger_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
window-vibrancy = "0.8.0"
oxideav-ico = "0.0.7"
png = "0.18.1"
tauri-plugin-shell = "2"
winreg = "0.56.0"
windows = { version = "0.62.2", features = ["Win32_UI_WindowsAndMessaging", "UI_ViewManagement"] }
tauri-plugin-store = "2"
zip = "8.6.0"

